export {
  OrganizationIdParamSchema,
  HotelIdParamSchema,
  ReservationIdParamSchema,
  CheckInRequestSchema,
  EarlyCheckInSchema,
  WalkInCheckInSchema,
  AssignRoomSchema,
  AutoAssignRoomSchema,
  UpgradeRoomSchema,
  ChangeRoomSchema,
  CheckoutSchema,
  ExpressCheckoutSchema,
  LateCheckoutSchema,
  NoShowSchema,
  ReinstateSchema,
  ExtendStaySchema,
  ShortenStaySchema,
  type CheckInRequestInput,
  type EarlyCheckInInput,
  type WalkInCheckInInput,
  type AssignRoomInput,
  type AutoAssignRoomInput,
  type UpgradeRoomInput,
  type ChangeRoomInput,
  type CheckoutInput,
  type ExpressCheckoutInput,
  type LateCheckoutInput,
  type NoShowInput,
  type ReinstateInput,
  type ExtendStayInput,
  type ShortenStayInput,
} from '@hms/schemas/checkinCheckout';



