export const propertyTypeOptions = [
  { value: "HOTEL", label: "Hotel" },
  { value: "RESORT", label: "Resort" },
  { value: "MOTEL", label: "Motel" },
  { value: "HOSTEL", label: "Hostel" },
  { value: "APARTMENT", label: "Apartment" },
  { value: "VILLA", label: "Villa" },
  { value: "B&B", label: "B&B" },
] as const;

export const currencyOptions = [
  { value: "USD", label: "USD — US Dollar" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British Pound" },
  { value: "AED", label: "AED — UAE Dirham" },
  { value: "SAR", label: "SAR — Saudi Riyal" },
  { value: "INR", label: "INR — Indian Rupee" },
  { value: "THB", label: "THB — Thai Baht" },
  { value: "SGD", label: "SGD — Singapore Dollar" },
  { value: "JPY", label: "JPY — Japanese Yen" },
  { value: "AUD", label: "AUD — Australian Dollar" },
  { value: "CAD", label: "CAD — Canadian Dollar" },
  { value: "CHF", label: "CHF — Swiss Franc" },
  { value: "HKD", label: "HKD — Hong Kong Dollar" },
  { value: "MYR", label: "MYR — Malaysian Ringgit" },
  { value: "CNY", label: "CNY — Chinese Yuan" },
  { value: "KRW", label: "KRW — South Korean Won" },
  { value: "NZD", label: "NZD — New Zealand Dollar" },
  { value: "BRL", label: "BRL — Brazilian Real" },
  { value: "MXN", label: "MXN — Mexican Peso" },
  { value: "ZAR", label: "ZAR — South African Rand" },
  { value: "TRY", label: "TRY — Turkish Lira" },
  { value: "RUB", label: "RUB — Russian Ruble" },
  { value: "SEK", label: "SEK — Swedish Krona" },
  { value: "NOK", label: "NOK — Norwegian Krone" },
  { value: "DKK", label: "DKK — Danish Krone" },
  { value: "PLN", label: "PLN — Polish Zloty" },
  { value: "EGP", label: "EGP — Egyptian Pound" },
  { value: "PHP", label: "PHP — Philippine Peso" },
  { value: "IDR", label: "IDR — Indonesian Rupiah" },
  { value: "VND", label: "VND — Vietnamese Dong" },
  { value: "NGN", label: "NGN — Nigerian Naira" },
  { value: "KES", label: "KES — Kenyan Shilling" },
  { value: "QAR", label: "QAR — Qatari Riyal" },
  { value: "OMR", label: "OMR — Omani Rial" },
  { value: "KWD", label: "KWD — Kuwaiti Dinar" },
  { value: "BHD", label: "BHD — Bahraini Dinar" },
  { value: "MAD", label: "MAD — Moroccan Dirham" },
  { value: "TND", label: "TND — Tunisian Dinar" },
  { value: "LKR", label: "LKR — Sri Lankan Rupee" },
  { value: "BDT", label: "BDT — Bangladeshi Taka" },
  { value: "NPR", label: "NPR — Nepalese Rupee" },
  { value: "PKR", label: "PKR — Pakistani Rupee" },
  { value: "MMK", label: "MMK — Myanmar Kyat" },
  { value: "LAK", label: "LAK — Lao Kip" },
  { value: "KHR", label: "KHR — Cambodian Riel" },
  { value: "MNT", label: "MNT — Mongolian Tugrik" },
  { value: "FJD", label: "FJD — Fijian Dollar" },
  { value: "XOF", label: "XOF — West African CFA" },
  { value: "XAF", label: "XAF — Central African CFA" },
] as const;

export const languageOptions = [
  { value: "en", label: "en — English" },
  { value: "fr", label: "fr — French" },
  { value: "es", label: "es — Spanish" },
  { value: "ar", label: "ar — Arabic" },
  { value: "zh", label: "zh — Chinese (Simplified)" },
  { value: "de", label: "de — German" },
  { value: "it", label: "it — Italian" },
  { value: "pt", label: "pt — Portuguese" },
  { value: "ja", label: "ja — Japanese" },
  { value: "ko", label: "ko — Korean" },
  { value: "nl", label: "nl — Dutch" },
  { value: "tr", label: "tr — Turkish" },
  { value: "ru", label: "ru — Russian" },
  { value: "pl", label: "pl — Polish" },
  { value: "th", label: "th — Thai" },
  { value: "vi", label: "vi — Vietnamese" },
  { value: "hi", label: "hi — Hindi" },
  { value: "ms", label: "ms — Malay" },
  { value: "id", label: "id — Indonesian" },
  { value: "sv", label: "sv — Swedish" },
  { value: "da", label: "da — Danish" },
  { value: "fi", label: "fi — Finnish" },
  { value: "nb", label: "nb — Norwegian" },
  { value: "he", label: "he — Hebrew" },
  { value: "ro", label: "ro — Romanian" },
  { value: "cs", label: "cs — Czech" },
  { value: "hu", label: "hu — Hungarian" },
  { value: "el", label: "el — Greek" },
  { value: "uk", label: "uk — Ukrainian" },
] as const;

export const smokingPolicyOptions = [
  { value: "NOT_ALLOWED", label: "Not allowed anywhere" },
  { value: "DESIGNATED_AREAS", label: "Designated areas only" },
  { value: "ALLOWED", label: "Allowed in smoking rooms" },
] as const;

export const petPolicyOptions = [
  { value: "NOT_ALLOWED", label: "Not allowed" },
  { value: "ALLOWED_FEE", label: "Allowed (fee applies)" },
  { value: "ALLOWED_FREE", label: "Allowed (free)" },
] as const;

export const timeFormatOptions = [
  { value: "12h", label: "12-hour (AM/PM)" },
  { value: "24h", label: "24-hour" },
] as const;

export const dateFormatOptions = [
  { value: "DD/MM/YYYY", label: "DD/MM/YYYY" },
  { value: "MM/DD/YYYY", label: "MM/DD/YYYY" },
  { value: "YYYY-MM-DD", label: "YYYY-MM-DD" },
] as const;
