export const PERMISSIONS = {
  // Organization
  ORGANIZATION: {
    CREATE: 'ORGANIZATION.CREATE',
    READ: 'ORGANIZATION.READ',
    UPDATE: 'ORGANIZATION.UPDATE',
    DELETE: 'ORGANIZATION.DELETE',
    MANAGE_SUBSCRIPTION: 'ORGANIZATION.MANAGE_SUBSCRIPTION',
    SUSPEND: 'ORGANIZATION.SUSPEND',
    ACTIVATE: 'ORGANIZATION.ACTIVATE',
  },

  // User
  USER: {
    READ: 'USER.READ',
    CREATE: 'USER.CREATE',
    UPDATE: 'USER.UPDATE',
    DELETE: 'USER.DELETE',
    MANAGE: 'USER.MANAGE',
  },

  // Role
  ROLE: {
    READ: 'ROLE.READ',
    CREATE: 'ROLE.CREATE',
    UPDATE: 'ROLE.UPDATE',
    DELETE: 'ROLE.DELETE',
    ASSIGN: 'ROLE.ASSIGN',
  },

  // Hotel
  HOTEL: {
    READ: 'HOTEL.READ',
    CREATE: 'HOTEL.CREATE',
    UPDATE: 'HOTEL.UPDATE',
    DELETE: 'HOTEL.DELETE',
    MANAGE: 'HOTEL.MANAGE',
  },

  // Room
  ROOM: {
    READ: 'ROOM.READ',
    CREATE: 'ROOM.CREATE',
    UPDATE: 'ROOM.UPDATE',
    DELETE: 'ROOM.DELETE',
    ASSIGN: 'ROOM.ASSIGN',
    UPGRADE: 'ROOM.UPGRADE',
    CHANGE: 'ROOM.CHANGE',
    BULK_UPDATE: 'ROOM.BULK_UPDATE',
    STATUS_UPDATE: 'ROOM.STATUS_UPDATE',
    OOO_MANAGE: 'ROOM.OOO_MANAGE',
    HISTORY_READ: 'ROOM.HISTORY_READ',
    MANAGE: 'ROOM.MANAGE',
  },

  // Reservation
  RESERVATION: {
    READ: 'RESERVATION.READ',
    CREATE: 'RESERVATION.CREATE',
    UPDATE: 'RESERVATION.UPDATE',
    DELETE: 'RESERVATION.DELETE',
    CANCEL: 'RESERVATION.CANCEL',
    CHECK_IN: 'RESERVATION.CHECK_IN',
    CHECK_OUT: 'RESERVATION.CHECK_OUT',
    ASSIGN_ROOM: 'RESERVATION.ASSIGN_ROOM',
    NO_SHOW: 'RESERVATION.NO_SHOW',
    SPLIT: 'RESERVATION.SPLIT',
  },

  // Check-in
  CHECKIN: {
    PERFORM: 'CHECKIN.PERFORM',
    EARLY: 'CHECKIN.EARLY',
    WALKIN: 'CHECKIN.WALKIN',
    OVERRIDE_BLACKLIST: 'CHECKIN.OVERRIDE_BLACKLIST',
    WAIVE_PREAUTH: 'CHECKIN.WAIVE_PREAUTH',
  },

  // Check-out
  CHECKOUT: {
    PERFORM: 'CHECKOUT.PERFORM',
    EXPRESS: 'CHECKOUT.EXPRESS',
    LATE: 'CHECKOUT.LATE',
    NO_SHOW: 'CHECKOUT.NO_SHOW',
    WAIVE_FEE: 'CHECKOUT.WAIVE_FEE',
    REINSTATE: 'CHECKOUT.REINSTATE',
  },

  // Front desk
  FRONTDESK: {
    DASHBOARD: 'FRONTDESK.DASHBOARD',
  },

  // Guest
  GUEST: {
    READ: 'GUEST.READ',
    CREATE: 'GUEST.CREATE',
    UPDATE: 'GUEST.UPDATE',
    DELETE: 'GUEST.DELETE',
    MERGE: 'GUEST.MERGE',
    UPDATE_VIP: 'GUEST.UPDATE_VIP',
  },

  // Housekeeping
  HOUSEKEEPING: {
    READ: 'HOUSEKEEPING.READ',
    CREATE: 'HOUSEKEEPING.CREATE',
    UPDATE: 'HOUSEKEEPING.UPDATE',
    ASSIGN: 'HOUSEKEEPING.ASSIGN',
    START_TASK: 'HOUSEKEEPING.START_TASK',
    COMPLETE_TASK: 'HOUSEKEEPING.COMPLETE_TASK',
    MARK_DND: 'HOUSEKEEPING.MARK_DND',
    CANCEL: 'HOUSEKEEPING.CANCEL',
    AUTO_GENERATE: 'HOUSEKEEPING.AUTO_GENERATE',
    INSPECT: 'HOUSEKEEPING.INSPECT',
    REPORT: 'HOUSEKEEPING.REPORT',
    SHIFT_MANAGE: 'HOUSEKEEPING.SHIFT_MANAGE',
    DASHBOARD_READ: 'HOUSEKEEPING.DASHBOARD_READ',
    LOST_FOUND_LOG: 'HOUSEKEEPING.LOST_FOUND_LOG',
    LOST_FOUND_UPDATE: 'HOUSEKEEPING.LOST_FOUND_UPDATE',
    LOST_FOUND_NOTIFY: 'HOUSEKEEPING.LOST_FOUND_NOTIFY',
  },

  // Inventory
  INVENTORY: {
    CREATE: 'INVENTORY.CREATE',
    READ: 'INVENTORY.READ',
    UPDATE: 'INVENTORY.UPDATE',
    DELETE: 'INVENTORY.DELETE',
    ADJUST: 'INVENTORY.ADJUST',
    CONSUME: 'INVENTORY.CONSUME',
    DASHBOARD: 'INVENTORY.DASHBOARD',
  },

  // Procurement
  PROCUREMENT: {
    READ: 'PROCUREMENT.READ',
    CREATE: 'PROCUREMENT.CREATE',
    UPDATE: 'PROCUREMENT.UPDATE',
    SUBMIT: 'PROCUREMENT.SUBMIT',
    APPROVE: 'PROCUREMENT.APPROVE',
    RECEIVE: 'PROCUREMENT.RECEIVE',
    CANCEL: 'PROCUREMENT.CANCEL',
    DASHBOARD: 'PROCUREMENT.DASHBOARD',
  },

  // Maintenance
  MAINTENANCE: {
    READ: 'MAINTENANCE.READ',
    CREATE: 'MAINTENANCE.CREATE',
    UPDATE: 'MAINTENANCE.UPDATE',
    ASSIGN: 'MAINTENANCE.ASSIGN',
    START: 'MAINTENANCE.START',
    PAUSE: 'MAINTENANCE.PAUSE',
    COMPLETE: 'MAINTENANCE.COMPLETE',
    VERIFY: 'MAINTENANCE.VERIFY',
    CANCEL: 'MAINTENANCE.CANCEL',
    ESCALATE: 'MAINTENANCE.ESCALATE',
    PARTS_LOG: 'MAINTENANCE.PARTS_LOG',
    GUEST_CHARGE: 'MAINTENANCE.GUEST_CHARGE',
    DASHBOARD_READ: 'MAINTENANCE.DASHBOARD_READ',
  },

  // Preventive maintenance
  PREVENTIVE: {
    READ: 'PREVENTIVE.READ',
    CREATE: 'PREVENTIVE.CREATE',
    UPDATE: 'PREVENTIVE.UPDATE',
    PAUSE: 'PREVENTIVE.PAUSE',
    GENERATE: 'PREVENTIVE.GENERATE',
  },

  // Asset
  ASSET: {
    READ: 'ASSET.READ',
    CREATE: 'ASSET.CREATE',
    UPDATE: 'ASSET.UPDATE',
    DELETE: 'ASSET.DELETE',
    EVALUATE: 'ASSET.EVALUATE',
  },

  // Night audit
  NIGHT_AUDIT: {
    RUN: 'NIGHT_AUDIT.RUN',
    PRE_CHECK: 'NIGHT_AUDIT.PRE_CHECK',
    VIEW_STATUS: 'NIGHT_AUDIT.VIEW_STATUS',
    VIEW_HISTORY: 'NIGHT_AUDIT.VIEW_HISTORY',
    VIEW_REPORT: 'NIGHT_AUDIT.VIEW_REPORT',
    ROLLBACK: 'NIGHT_AUDIT.ROLLBACK',
  },

  // POS
  POS: {
    READ_ORDER: 'POS.READ_ORDER',
    CREATE_ORDER: 'POS.CREATE_ORDER',
    MODIFY_ORDER: 'POS.MODIFY_ORDER',
    CLOSE_ORDER: 'POS.CLOSE_ORDER',
    VOID_ORDER: 'POS.VOID_ORDER',
    REOPEN_ORDER: 'POS.REOPEN_ORDER',
    POST_ROOM_CHARGE: 'POS.POST_ROOM_CHARGE',
    SPLIT_ORDER: 'POS.SPLIT_ORDER',
    TRANSFER_ORDER: 'POS.TRANSFER_ORDER',
    MANAGE_OUTLET: 'POS.MANAGE_OUTLET',
    MANAGE_MENU: 'POS.MANAGE_MENU',
    VIEW_DASHBOARD: 'POS.VIEW_DASHBOARD',
    VIEW_REPORTS: 'POS.VIEW_REPORTS',
  },

  // Channel manager
  CHANNEL: {
    READ: 'CHANNEL.READ',
    MANAGE: 'CHANNEL.MANAGE',
    ACTIVATE: 'CHANNEL.ACTIVATE',
    DEACTIVATE: 'CHANNEL.DEACTIVATE',
    MAP: 'CHANNEL.MAP',
    SYNC: 'CHANNEL.SYNC',
    READ_LOGS: 'CHANNEL.READ_LOGS',
  },

  // Admin
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

// Helper type
type NestedValueOf<T> = T extends string ? T : { [K in keyof T]: NestedValueOf<T[K]> }[keyof T];

export type Permission = NestedValueOf<typeof PERMISSIONS>;
