export {
  OrganizationIdParamSchema,
  HotelIdParamSchema,
  TaskIdParamSchema,
  InspectionIdParamSchema,
  ShiftIdParamSchema,
  LostFoundItemIdParamSchema,
  StaffIdParamSchema,
  RoomIdParamSchema,
  HousekeepingTaskTypeSchema,
  HousekeepingTaskStatusSchema,
  InspectionOutcomeSchema,
  ShiftStatusSchema,
  LostFoundStatusSchema,
  CreateTaskSchema,
  TaskListQuerySchema,
  UpdateTaskSchema,
  AssignTaskSchema,
  StartTaskSchema,
  CompleteTaskSchema,
  DndTaskSchema,
  CancelTaskSchema,
  AutoGenerateTasksSchema,
  BulkAssignSchema,
  InspectionScoresSchema,
  InspectionFailureItemSchema,
  SubmitInspectionSchema,
  InspectionListQuerySchema,
  StaffScoreQuerySchema,
  CreateShiftSchema,
  UpdateShiftSchema,
  AssignShiftStaffSchema,
  ShiftListQuerySchema,
  StaffWorkloadQuerySchema,
  DashboardQuerySchema,
  CreateLostFoundItemSchema,
  UpdateLostFoundItemSchema,
  LostFoundListQuerySchema,
  NotifyLostFoundSchema,
  type CreateTaskInput,
  type TaskListQueryInput,
  type UpdateTaskInput,
  type AssignTaskInput,
  type StartTaskInput,
  type CompleteTaskInput,
  type DndTaskInput,
  type CancelTaskInput,
  type AutoGenerateTasksInput,
  type BulkAssignInput,
  type SubmitInspectionInput,
  type InspectionListQueryInput,
  type StaffScoreQueryInput,
  type CreateShiftInput,
  type UpdateShiftInput,
  type AssignShiftStaffInput,
  type ShiftListQueryInput,
  type StaffWorkloadQueryInput,
  type DashboardQueryInput,
  type CreateLostFoundItemInput,
  type UpdateLostFoundItemInput,
  type LostFoundListQueryInput,
  type NotifyLostFoundInput,
} from './housekeeping.schema';

export type { HousekeepingDashboardSummary } from './housekeeping.types';
